### ISSUE TITLE
Lifecycle hooks appear in methods instead of on their own.

### ISSUE THREAD

**Issue by supertiger1234** [misha/vue-declassify#3]
Stuff like `mounted` and `beforeMount` functions get moved inside `methods` instead of outside

**Comment by misha** [comment]
Basically all lifecycle methods are treated like this apparently. Thanks for the report, I'll take a look.

**Comment by supertiger1234** [comment]
There is also a small problem with `@Watch` if you dont mind me pointing out.
I guess I'm just doing this in a way but i stack watchers like this:
```js
@Watch("currentChannelID")
@Watch("currentServerID")
@Watch("currentTab")
saveLastSelected() {
  // code
}  
``` 
this gets turned into only one:
```js
watch: {
  currentChannelID: {
    handler() {
       //code
    }
```
I also reference `saveLastSelected` in my methods which doesnt work as that function doesnt exist anymore.

I'm probably asking for too much, sorry!
thanks for the quick replies though ^^

**Comment by misha** [comment]
@supertiger1234 I changed method handling such that methods whose names are lifecycle hooks are not placed in the `methods` hash, but rather appear on their own.

There are tests, check out the commit referenced above.

**Comment by supertiger1234** [comment]
Epic, I'll test it out in a bit, thanks!

**Comment by supertiger1234** [comment]
Works fine :)
