### ISSUE TITLE
Script setup?

### ISSUE THREAD

**Issue by mobsense** [misha/vue-declassify#5]
Any thoughts on supporting Vue 3 and emitting code in script setup style?

**Comment by misha** [comment]
@mobsense Thanks for your interest, and apologies for the late reply.

I think there are two requests so I'll address them separately.

> supporting Vue 3

I think I intended for this library to be something that enables you to switch to Vue 3 with basically no additional manual changes. Is there a specific part of the current output that does not support Vue 3?

If it's a matter of outputting the values to different keys to satisfy an updated interface, I can absolutely add that I think.

> script setup style

This would probably work best as an additional transform to maintain separation of concerns (going from "object-style" to "script setup object style"). It does seem to fit within what this package would like to offer and doesn't seem too difficult, either.

---

Is there something here that you would particularly need soon?

**Comment by mobsense** [comment]
Actually, I mercilessly hacked the package to suite my needs and it worked great.
I wanted to convert several Vue 2 apps that used class components to Vue 2.7 with script setup. We chose this as our evolutionary path to Vue 3 as several of our dependencies don't have stable Vue 3 support yet (Vuetify being one).

The hacked tool did 70% of the work on each file and I had a set of manual fixes after that. There was a script setup learning curve to get the right output.  

But it saved countless hours. Thank you for the tool, it was a great starting point.

**Comment by misha** [comment]
@mobsense Glad to hear that! Hopefully other people looking to do 2 to 3 migration will be able to do the same. If there's something you think is generally useful to the package, feel free to send a PR and I'll merge it, too.

Cheers!
